<a href="https://colab.research.google.com/github/gerardopdm/ml-ejemplos/blob/master/Ejemplos_Tuplas_Listas_Arreglos.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
tupla1=(5,3)

In [2]:
tupla1

(5, 3)

In [3]:
tupla1[0]

5

In [4]:
tupla1[1]

3

In [5]:
tupla1[2]=4

TypeError: ignored

In [0]:
lista1=[1,2,3,4,1.2]

In [7]:
lista1

[1, 2, 3, 4, 1.2]

In [8]:
lista1=lista1/3

TypeError: ignored

In [0]:
import numpy as np

In [0]:
arreglo1=np.asarray(lista1)

In [11]:
arreglo1

array([1. , 2. , 3. , 4. , 1.2])

In [0]:
arreglo1=arreglo1/2

In [13]:
arreglo1

array([0.5, 1. , 1.5, 2. , 0.6])

In [0]:
arreglo2=np.array([11,22,33,44,55,66,77,88])

In [15]:
arreglo2

array([11, 22, 33, 44, 55, 66, 77, 88])

In [16]:
arreglo2[0]

11

In [17]:
arreglo2[1]

22

In [18]:
arreglo2[0:2]

array([11, 22])

In [19]:
arreglo2[3]

44

In [20]:
arreglo2[-1]

88

In [21]:
arreglo2[1:]

array([22, 33, 44, 55, 66, 77, 88])

In [22]:
arreglo2[:-2]

array([11, 22, 33, 44, 55, 66])

In [24]:
for x in arreglo2:
  print(x)

11
22
33
44
55
66
77
88


In [25]:
for i,x in enumerate(arreglo2):
  print(i,x)

0 11
1 22
2 33
3 44
4 55
5 66
6 77
7 88
